### ISSUE TITLE
No references in paper.md

### ISSUE THREAD

**Issue by stuartcampbell** [scikit-beam/NeuNorm#5]
I notice that you have a `paper.bib` with some references in, but they don't appear in the actual paper.  Is this intended ?

**Comment by JeanBilheux** [comment]
Well yes. I wanted to reference the libraries I'm using (in the code) but it's not related to the algorithm itself, for which I do not have any reference.

**Comment by stuartcampbell** [comment]
Looking at other JOSS papers, they tend to cite the packages they've used.

**Comment by stuartcampbell** [comment]
Adding link to openjournals/joss-reviews#815

**Comment by stuartcampbell** [comment]
Hi @JeanBilheux  I found this webpage; https://scipy.org/citing.html.  Do you think it's worth adding the reference to numpy that's listed here as well ?
